feat(api): setup routes
Duunis/Pollus pull request #27
Opened 2022-10-10 16:21 UTC by vanhanenjjv

2022-10-11 06:34 UTC, aarotoiv approved these changes
Veri nais

2022-10-11 07:49 UTC, tominkki requested changes

2022-10-11 07:49 UTC, tominkki commented on api/src/routes/admin/quizzes/index.rs
> +        None => Response::error("Admin key is missing from the request", 400)
Should we use rather 401 Unauthorized?

2022-10-11 07:49 UTC, tominkki commented on api/src/routes/admin/quizzes/submissions.rs
> +        None => Response::error("Admin key is missing from the request", 400)
Same here

2022-10-30 17:49 UTC, vanhanenjjv commented on api/src/routes/admin/quizzes/index.rs
> +        None => Response::error("Admin key is missing from the request", 400)
Yes. :)

2022-10-30 17:49 UTC, vanhanenjjv commented on api/src/routes/admin/quizzes/submissions.rs
> +        None => Response::error("Admin key is missing from the request", 400)
Yes. :)

2022-10-30 17:54 UTC, merged